=== Antoniocb3/lenguajemarcas/temas/unidad6/repasoexamen/examen25032022/ej1/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="companiaav">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="compania">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="aviones" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="codav"/>
                                        <xs:element name="modeloav">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                   <xs:enumeration value="Airbus A319"/>
                                                   <xs:enumeration value="Airbus A320"/>
                                                   <xs:enumeration value="Boeling 757"/>
                                                   <xs:enumeration value="Boeling 777"/>
                                                </xs:restriction>
                                             </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="numpas">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="50"/>
                                                <xs:maxInclusive value="300"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:sequence>
                                <xs:element name="aeropuerto" minOccurs="2" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="codaer"/>
                                            <xs:element name="ciudad"/>
                                            <xs:element name="pais"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                    
                                </xs:element>
                                <xs:sequence>
                                    <xs:element name="ruta">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="codru"/>
                                                <xs:element name="aesalida"/>
                                                <xs:element name="aellegada"/>
                                                <xs:element name="numvuelo">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                        <xs:pattern value="[A-Z]{2}[0-9]{4}"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="hdespegue"/>
                                                <xs:element name="haterrizaje"/>
                                                <xs:element name="avionutil">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                          <xs:enumeration value="Airbus A319"/>
                                                          <xs:enumeration value="Airbus A320"/>
                                                          <xs:enumeration value="Boeling 757"/>
                                                          <xs:enumeration value="Boeling 777"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:sequence>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    </xs:schema>

=== Antoniocb3/lenguajemarcas/temas/unidad6/repasoexamen/examen25032022/ej1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<companiaav xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicio1.xsd">


    <compania>
        <aviones>
            <codav>050</codav>
            <modeloav>Airbus A320</modeloav>
            <numpas>189</numpas>
        </aviones>
        <aviones>
            <codav>051</codav>
            <modeloav>Airbus A319</modeloav>
            <numpas>50</numpas>
        </aviones>

        <aeropuerto>
            <codaer>032</codaer>
            <ciudad>Valencia</ciudad>
            <pais>España</pais>
        </aeropuerto>
        <aeropuerto>
            <codaer>032</codaer>
            <ciudad>Murcia</ciudad>
            <pais>España</pais>
        </aeropuerto>

        <ruta>
            <codru>060</codru>
            <aesalida>Valencia</aesalida>
            <aellegada>Murcia</aellegada>
            <numvuelo>AA4312</numvuelo>
            <hdespegue>09:00</hdespegue>
            <haterrizaje>12:00</haterrizaje>
            <avionutil>Airbus A319</avionutil>
        </ruta>
    </compania>












</companiaav>
