<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errores [

    <!ELEMENT errores (ejercicio+)>
    <!ELEMENT ejercicio (nombre, error*)>
    <!ATTLIST ejercicio id ID #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT error (linea, descripcion)>
    <!ATTLIST error fecha CDATA >
    <!ATTLIST error hora CDATA >
    <!ELEMENT linea (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>


]>
<errores>
  <ejercicio>
    <nombre>Ejercicio DTD 5</nombre>
    <error fecha="14/02/2022" hora="12:15">
      <linea>2</linea>
      <descripcion>DOCTYPE no declarado</descripcion>
    </error>

    <error fecha="14/02/2022" hora="12:15">
      <linea>3</linea>
      <descripcion>No hay etiqueta ciudad</descripcion>
    </error>



  </ejercicio> 

  <ejercicio>
    <nombre>Ejercicio DTD 6</nombre>
    <error fecha="14/02/2022" hora="12:15">
      <linea>2</linea>
      <descripcion>No existia el nodo raiz</descripcion>
    </error>

    <error fecha="14/02/2022" hora="12:15">
      <linea>3</linea>
      <descripcion>No hay etiqueta ciudad</descripcion>
    </error>



  </ejercicio> 


</errores>